services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance/site.db:/app/site.db
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=0b53868cef9425590509a6c9c51762ce
    command: ["flask", "--app", "application:app", "run",  "--host", "0.0.0.0"] 
    