version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance/site.db:/app/site.db
    environment:
      - FLASK_ENV=development
    command: python application.py
